// <auto-generated />
using System;
using B2B_Procurement___Order_Management_Platform.src.ArtMarket.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace B2B_Procurement___Order_Management_Platform.Migrations
{
    [DbContext(typeof(AppDb))]
    partial class AppDbModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Artist", b =>
                {
                    b.Property<string>("ArtistId")
                        .HasColumnType("text");

                    b.Property<string>("ArtistDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfileImage")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArtistId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Artists");
                });

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Artwork", b =>
                {
                    b.Property<string>("ArtId")
                        .HasColumnType("text");

                    b.Property<string>("ArtistId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ArtId");

                    b.HasIndex("ArtistId");

                    b.ToTable("Artworks");
                });

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Buyer", b =>
                {
                    b.Property<string>("BuyerId")
                        .HasColumnType("text");

                    b.Property<string>("BuyerDisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BuyerId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Order", b =>
                {
                    b.Property<string>("OrderId")
                        .HasColumnType("text");

                    b.Property<string>("ArtId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ArtistId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuyerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OrderId");

                    b.HasIndex("ArtId");

                    b.HasIndex("ArtistId");

                    b.HasIndex("BuyerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Subscription", b =>
                {
                    b.Property<string>("SubscriptionId")
                        .HasColumnType("text");

                    b.Property<string>("ArtistId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Tier")
                        .HasColumnType("integer");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("ArtistId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasColumnType("text");

                    b.Property<string>("NormalizedUserName")
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Artist", b =>
                {
                    b.HasOne("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.User", "User")
                        .WithOne("Artist")
                        .HasForeignKey("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Artist", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Artwork", b =>
                {
                    b.HasOne("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Artist", "Artist")
                        .WithMany("Artworks")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Buyer", b =>
                {
                    b.HasOne("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.User", "User")
                        .WithOne("Buyer")
                        .HasForeignKey("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Buyer", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Order", b =>
                {
                    b.HasOne("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Artwork", "ArtWork")
                        .WithMany("Orders")
                        .HasForeignKey("ArtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Artist", "Artist")
                        .WithMany("Orders")
                        .HasForeignKey("ArtistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Buyer", "Buyer")
                        .WithMany("Orders")
                        .HasForeignKey("BuyerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArtWork");

                    b.Navigation("Artist");

                    b.Navigation("Buyer");
                });

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Subscription", b =>
                {
                    b.HasOne("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Artist", "Artist")
                        .WithOne("Subscription")
                        .HasForeignKey("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Subscription", "ArtistId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Artist");
                });

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Artist", b =>
                {
                    b.Navigation("Artworks");

                    b.Navigation("Orders");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Artwork", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.Buyer", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("B2B_Procurement___Order_Management_Platform.ArtMarket.Domain.Models.User", b =>
                {
                    b.Navigation("Artist");

                    b.Navigation("Buyer");
                });
#pragma warning restore 612, 618
        }
    }
}
